 create table Person(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar not null ,
    age int check ( age > 0 ),
    email varchar UNIQUE
);

alter table person add column address varchar NOT NULL;